var annotated_dup =
[
    [ "AuxPort", "namespace_aux_port.html", [
      [ "Audio", "namespace_aux_port_1_1_audio.html", [
        [ "IIR", "namespace_aux_port_1_1_audio_1_1_i_i_r.html", [
          [ "Butterworth", "class_aux_port_1_1_audio_1_1_i_i_r_1_1_butterworth.html", "class_aux_port_1_1_audio_1_1_i_i_r_1_1_butterworth" ],
          [ "Engine", "class_aux_port_1_1_audio_1_1_i_i_r_1_1_engine.html", "class_aux_port_1_1_audio_1_1_i_i_r_1_1_engine" ],
          [ "FirstOrder", "class_aux_port_1_1_audio_1_1_i_i_r_1_1_first_order.html", "class_aux_port_1_1_audio_1_1_i_i_r_1_1_first_order" ],
          [ "General", "class_aux_port_1_1_audio_1_1_i_i_r_1_1_general.html", "class_aux_port_1_1_audio_1_1_i_i_r_1_1_general" ],
          [ "ParametricEQ", "class_aux_port_1_1_audio_1_1_i_i_r_1_1_parametric_e_q.html", "class_aux_port_1_1_audio_1_1_i_i_r_1_1_parametric_e_q" ]
        ] ],
        [ "ADSR", "class_aux_port_1_1_audio_1_1_a_d_s_r.html", "class_aux_port_1_1_audio_1_1_a_d_s_r" ],
        [ "Assymetric", "class_aux_port_1_1_audio_1_1_assymetric.html", "class_aux_port_1_1_audio_1_1_assymetric" ],
        [ "BartlettFIR", "class_aux_port_1_1_audio_1_1_bartlett_f_i_r.html", "class_aux_port_1_1_audio_1_1_bartlett_f_i_r" ],
        [ "BartlettHannFIR", "class_aux_port_1_1_audio_1_1_bartlett_hann_f_i_r.html", "class_aux_port_1_1_audio_1_1_bartlett_hann_f_i_r" ],
        [ "BipolarSawtooth", "class_aux_port_1_1_audio_1_1_bipolar_sawtooth.html", "class_aux_port_1_1_audio_1_1_bipolar_sawtooth" ],
        [ "BlackmanFIR", "class_aux_port_1_1_audio_1_1_blackman_f_i_r.html", "class_aux_port_1_1_audio_1_1_blackman_f_i_r" ],
        [ "BlackmanHarrisFIR", "class_aux_port_1_1_audio_1_1_blackman_harris_f_i_r.html", "class_aux_port_1_1_audio_1_1_blackman_harris_f_i_r" ],
        [ "Buffer", "class_aux_port_1_1_audio_1_1_buffer.html", "class_aux_port_1_1_audio_1_1_buffer" ],
        [ "Convolution", "class_aux_port_1_1_audio_1_1_convolution.html", "class_aux_port_1_1_audio_1_1_convolution" ],
        [ "DiscreteCosineTransform", "class_aux_port_1_1_audio_1_1_discrete_cosine_transform.html", "class_aux_port_1_1_audio_1_1_discrete_cosine_transform" ],
        [ "DiscreteFourierTransform", "class_aux_port_1_1_audio_1_1_discrete_fourier_transform.html", "class_aux_port_1_1_audio_1_1_discrete_fourier_transform" ],
        [ "Distortion", "class_aux_port_1_1_audio_1_1_distortion.html", null ],
        [ "FIR", "class_aux_port_1_1_audio_1_1_f_i_r.html", "class_aux_port_1_1_audio_1_1_f_i_r" ],
        [ "FlatFIR", "class_aux_port_1_1_audio_1_1_flat_f_i_r.html", "class_aux_port_1_1_audio_1_1_flat_f_i_r" ],
        [ "FourierTransform", "class_aux_port_1_1_audio_1_1_fourier_transform.html", "class_aux_port_1_1_audio_1_1_fourier_transform" ],
        [ "HammingFIR", "class_aux_port_1_1_audio_1_1_hamming_f_i_r.html", "class_aux_port_1_1_audio_1_1_hamming_f_i_r" ],
        [ "HannFIR", "class_aux_port_1_1_audio_1_1_hann_f_i_r.html", "class_aux_port_1_1_audio_1_1_hann_f_i_r" ],
        [ "KPString", "class_aux_port_1_1_audio_1_1_k_p_string.html", "class_aux_port_1_1_audio_1_1_k_p_string" ],
        [ "NuttallFIR", "class_aux_port_1_1_audio_1_1_nuttall_f_i_r.html", "class_aux_port_1_1_audio_1_1_nuttall_f_i_r" ],
        [ "Oscillator", "class_aux_port_1_1_audio_1_1_oscillator.html", "class_aux_port_1_1_audio_1_1_oscillator" ],
        [ "Pan", "class_aux_port_1_1_audio_1_1_pan.html", "class_aux_port_1_1_audio_1_1_pan" ],
        [ "PBSaw", "class_aux_port_1_1_audio_1_1_p_b_saw.html", "class_aux_port_1_1_audio_1_1_p_b_saw" ],
        [ "PBWSaw", "class_aux_port_1_1_audio_1_1_p_b_w_saw.html", "class_aux_port_1_1_audio_1_1_p_b_w_saw" ],
        [ "RectangleFIR", "class_aux_port_1_1_audio_1_1_rectangle_f_i_r.html", "class_aux_port_1_1_audio_1_1_rectangle_f_i_r" ],
        [ "Sine", "class_aux_port_1_1_audio_1_1_sine.html", "class_aux_port_1_1_audio_1_1_sine" ],
        [ "Square", "class_aux_port_1_1_audio_1_1_square.html", "class_aux_port_1_1_audio_1_1_square" ],
        [ "Triangle", "class_aux_port_1_1_audio_1_1_triangle.html", "class_aux_port_1_1_audio_1_1_triangle" ],
        [ "UnipolarSawtooth", "class_aux_port_1_1_audio_1_1_unipolar_sawtooth.html", "class_aux_port_1_1_audio_1_1_unipolar_sawtooth" ],
        [ "WhiteNoise", "class_aux_port_1_1_audio_1_1_white_noise.html", "class_aux_port_1_1_audio_1_1_white_noise" ],
        [ "Window", "class_aux_port_1_1_audio_1_1_window.html", "class_aux_port_1_1_audio_1_1_window" ]
      ] ],
      [ "Extensions", "namespace_aux_port_1_1_extensions.html", [
        [ "AuxCurl", "class_aux_port_1_1_extensions_1_1_aux_curl.html", "class_aux_port_1_1_extensions_1_1_aux_curl" ]
      ] ],
      [ "Simd", "namespace_aux_port_1_1_simd.html", [
        [ "Float128", "class_aux_port_1_1_simd_1_1_float128.html", "class_aux_port_1_1_simd_1_1_float128" ],
        [ "Float256", "class_aux_port_1_1_simd_1_1_float256.html", "class_aux_port_1_1_simd_1_1_float256" ],
        [ "FloatingPoint", "class_aux_port_1_1_simd_1_1_floating_point.html", "class_aux_port_1_1_simd_1_1_floating_point" ]
      ] ],
      [ "About", "class_aux_port_1_1_about.html", null ],
      [ "AuxPascal", "class_aux_port_1_1_aux_pascal.html", "class_aux_port_1_1_aux_pascal" ],
      [ "AuxSeries", "class_aux_port_1_1_aux_series.html", "class_aux_port_1_1_aux_series" ],
      [ "AuxSeriesEngine", "class_aux_port_1_1_aux_series_engine.html", "class_aux_port_1_1_aux_series_engine" ],
      [ "BinaryFile", "class_aux_port_1_1_binary_file.html", "class_aux_port_1_1_binary_file" ],
      [ "Case", "class_aux_port_1_1_case.html", "class_aux_port_1_1_case" ],
      [ "Casters", "class_aux_port_1_1_casters.html", null ],
      [ "CircularBuffer", "class_aux_port_1_1_circular_buffer.html", "class_aux_port_1_1_circular_buffer" ],
      [ "CSV", "class_aux_port_1_1_c_s_v.html", "class_aux_port_1_1_c_s_v" ],
      [ "Env", "class_aux_port_1_1_env.html", null ],
      [ "Error", "class_aux_port_1_1_error.html", "class_aux_port_1_1_error" ],
      [ "Expansions", "class_aux_port_1_1_expansions.html", "class_aux_port_1_1_expansions" ],
      [ "FastRandomFloat", "class_aux_port_1_1_fast_random_float.html", "class_aux_port_1_1_fast_random_float" ],
      [ "File", "class_aux_port_1_1_file.html", "class_aux_port_1_1_file" ],
      [ "ICasters", "class_aux_port_1_1_i_casters.html", "class_aux_port_1_1_i_casters" ],
      [ "ILog", "class_aux_port_1_1_i_log.html", "class_aux_port_1_1_i_log" ],
      [ "Interpolation", "class_aux_port_1_1_interpolation.html", "class_aux_port_1_1_interpolation" ],
      [ "Logger", "class_aux_port_1_1_logger.html", null ],
      [ "MD5", "class_aux_port_1_1_m_d5.html", null ],
      [ "String", "class_aux_port_1_1_string.html", "class_aux_port_1_1_string" ],
      [ "StringPair", "class_aux_port_1_1_string_pair.html", "class_aux_port_1_1_string_pair" ],
      [ "Terms", "class_aux_port_1_1_terms.html", "class_aux_port_1_1_terms" ],
      [ "TextFile", "class_aux_port_1_1_text_file.html", "class_aux_port_1_1_text_file" ],
      [ "TextFormat", "class_aux_port_1_1_text_format.html", "class_aux_port_1_1_text_format" ],
      [ "Time", "class_aux_port_1_1_time.html", "class_aux_port_1_1_time" ],
      [ "Timer", "class_aux_port_1_1_timer.html", "class_aux_port_1_1_timer" ],
      [ "Utility", "class_aux_port_1_1_utility.html", null ]
    ] ]
];