var namespace_aux_port =
[
    [ "Audio", "namespace_aux_port_1_1_audio.html", "namespace_aux_port_1_1_audio" ],
    [ "Extensions", "namespace_aux_port_1_1_extensions.html", "namespace_aux_port_1_1_extensions" ],
    [ "Simd", "namespace_aux_port_1_1_simd.html", "namespace_aux_port_1_1_simd" ],
    [ "About", "class_aux_port_1_1_about.html", null ],
    [ "AuxPascal", "class_aux_port_1_1_aux_pascal.html", "class_aux_port_1_1_aux_pascal" ],
    [ "AuxSeries", "class_aux_port_1_1_aux_series.html", "class_aux_port_1_1_aux_series" ],
    [ "AuxSeriesEngine", "class_aux_port_1_1_aux_series_engine.html", "class_aux_port_1_1_aux_series_engine" ],
    [ "BinaryFile", "class_aux_port_1_1_binary_file.html", "class_aux_port_1_1_binary_file" ],
    [ "Case", "class_aux_port_1_1_case.html", "class_aux_port_1_1_case" ],
    [ "Casters", "class_aux_port_1_1_casters.html", null ],
    [ "CircularBuffer", "class_aux_port_1_1_circular_buffer.html", "class_aux_port_1_1_circular_buffer" ],
    [ "CSV", "class_aux_port_1_1_c_s_v.html", "class_aux_port_1_1_c_s_v" ],
    [ "Env", "class_aux_port_1_1_env.html", null ],
    [ "Error", "class_aux_port_1_1_error.html", "class_aux_port_1_1_error" ],
    [ "Expansions", "class_aux_port_1_1_expansions.html", "class_aux_port_1_1_expansions" ],
    [ "FastRandomFloat", "class_aux_port_1_1_fast_random_float.html", "class_aux_port_1_1_fast_random_float" ],
    [ "File", "class_aux_port_1_1_file.html", "class_aux_port_1_1_file" ],
    [ "ICasters", "class_aux_port_1_1_i_casters.html", "class_aux_port_1_1_i_casters" ],
    [ "ILog", "class_aux_port_1_1_i_log.html", "class_aux_port_1_1_i_log" ],
    [ "Interpolation", "class_aux_port_1_1_interpolation.html", "class_aux_port_1_1_interpolation" ],
    [ "Logger", "class_aux_port_1_1_logger.html", null ],
    [ "MD5", "class_aux_port_1_1_m_d5.html", null ],
    [ "String", "class_aux_port_1_1_string.html", "class_aux_port_1_1_string" ],
    [ "StringPair", "class_aux_port_1_1_string_pair.html", "class_aux_port_1_1_string_pair" ],
    [ "Terms", "class_aux_port_1_1_terms.html", "class_aux_port_1_1_terms" ],
    [ "TextFile", "class_aux_port_1_1_text_file.html", "class_aux_port_1_1_text_file" ],
    [ "TextFormat", "class_aux_port_1_1_text_format.html", "class_aux_port_1_1_text_format" ],
    [ "Time", "class_aux_port_1_1_time.html", "class_aux_port_1_1_time" ],
    [ "Timer", "class_aux_port_1_1_timer.html", "class_aux_port_1_1_timer" ],
    [ "Utility", "class_aux_port_1_1_utility.html", null ],
    [ "ColourType", "namespace_aux_port.html#a7991652d34d5bd9e7be89163bcea3a51", null ],
    [ "LogType", "namespace_aux_port.html#a57041d7d75811675aec62cfb9ba07d24", [
      [ "Success", "namespace_aux_port.html#a57041d7d75811675aec62cfb9ba07d24a505a83f220c02df2f85c3810cd9ceb38", null ],
      [ "Warning", "namespace_aux_port.html#a57041d7d75811675aec62cfb9ba07d24a0eaadb4fcb48a0a0ed7bc9868be9fbaa", null ],
      [ "Info", "namespace_aux_port.html#a57041d7d75811675aec62cfb9ba07d24a4059b0251f66a18cb56f544728796875", null ],
      [ "Error", "namespace_aux_port.html#a57041d7d75811675aec62cfb9ba07d24a902b0d55fddef6f8d651fe1035b7d4bd", null ]
    ] ]
];